name: .NET Core Push Build

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'releases/**'

jobs:
  push_build:
    name: Build on push
    uses: ./.github/workflows/dotnetbuild.yml
    with:
      build-configuration: Release
