name: .NET Core Release Publish

on:
  release:
    types: [published]

env:
  GITHUB_NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  DEPLOY_DIR: publish_${{ github.run_number }}_${{ github.run_attempt }}

jobs:
  release_build:
    name: Build on release
    uses: ./.github/workflows/dotnetbuild.yml
    with:
      build-configuration: Release

  release_publish:
    name: Publish on release
    needs: release_build
    runs-on: windows-latest
    steps:
    # Download build output
    - name: Download nuget artifact
      uses: actions/download-artifact@v3
      with:
        name: nuget-build-output
        path: ${{ env.DEPLOY_DIR }}
    # Attach build output to release
    - name: Attach nuget to release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.DEPLOY_DIR }}\*.nupkg
    # Publish build output
    - name: Deploy to GitHub Package Repository with dotnet
      run: |
        dotnet nuget add source ${{ env.GITHUB_NUGET_URL }} --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ".\${{ env.DEPLOY_DIR }}\*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
