name: .NET Core Release Publish
description: 'Buillds, Tests, and Releases on a repository release publish.'

on:
  release:
    types: [published]

env:
  GITHUB_NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

inputs:
  build-configuration:
    description: 'The build configuration. If omitted, Release is built.'
    required: false
    default: Release

jobs:
  release_build:
    name: Build on release
    uses: ./.github/workflows/dotnetbuild.yml
    with:
      build-configuration: ${{ inputs.build-configuration }}

  release_publish:
    name: Publish on release
    needs: release_build
    runs-on: windows-latest
    steps:
    # Download build output
    - name: Download nuget artifact
      uses: actions/download-artifact@v3
      with:
        name: nuget-build-output
        path: deploy
    # Attach build output to release
    - name: Attach nuget to release
      uses: softprops/action-gh-release@v1
        with:
          files: deploy\*.nupkg
    # Publish build output
    - name: Deploy to GitHub Package Repository with dotnet
      run: |
        dotnet nuget add source ${{ env.GITHUB_NUGET_URL }} --name github --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push ".\deploy\*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
